# Generated by Django 5.0.4 on 2024-04-12 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_employee_cnic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cell_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('cnic', models.CharField(max_length=15)),
                ('father_name', models.CharField(max_length=100)),
                ('father_dob', models.DateField()),
                ('father_cnic', models.CharField(max_length=15)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_dob', models.DateField()),
                ('mother_cnic', models.CharField(max_length=15)),
                ('course', models.CharField(choices=[('IELTS', 'IELTS'), ('PTE', 'PTE'), ('TOFEL', 'TOFEL'), ('GRE', 'GRE'), ('GMAT', 'GMAT')], max_length=10)),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=100)),
                ('percentage_or_cgpa', models.CharField(max_length=20)),
                ('passing_year', models.PositiveIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.student')),
            ],
        ),
    ]
