# Generated by Django 5.0.4 on 2024-04-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_student_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='student',
            name='father_cnic',
        ),
        migrations.RemoveField(
            model_name='student',
            name='father_dob',
        ),
        migrations.RemoveField(
            model_name='student',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mother_cnic',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mother_dob',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mother_name',
        ),
        migrations.AlterField(
            model_name='student',
            name='cnic',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
