# Generated by Django 5.0.4 on 2024-06-15 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_student_academics_student_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('SSC', 'SSC'), ('HSSC', 'HSSC'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('PhD', 'PhD')], max_length=10)),
                ('institute', models.CharField(max_length=100)),
                ('passing_year', models.CharField(max_length=4)),
                ('percentage_or_cgpa', models.CharField(max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='portal.student')),
            ],
        ),
    ]
