# Generated by Django 5.0.4 on 2024-06-16 00:06

import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree_file',
            field=models.FileField(blank=True, null=True, upload_to=portal.models.PathAndRename()),
        ),
    ]
