# Generated by Django 5.0.4 on 2024-06-16 08:30

import django.db.models.deletion
import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_education_degree_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CNIC', 'CNIC'), ('Passport', 'Passport'), ('PassportSizePic', 'Passport Size Picture'), ('ExperienceLetter', 'Experience Letter'), ('CV', 'CV'), ('LetterOfRecommendation', 'Letter of Recommendation'), ('Resume', 'Resume')], max_length=50)),
                ('document_file', models.FileField(upload_to=portal.models.PathAndRename(), validators=[portal.models.validate_file_size])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_documents', to='portal.student')),
            ],
        ),
    ]
