# Generated by Django 5.0.4 on 2024-06-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_personaldocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldocument',
            name='document_type',
            field=models.CharField(choices=[('CNIC_Front', 'CNIC Front'), ('CNIC_Back', 'CNIC Back'), ('Passport', 'Passport'), ('PassportSizePic', 'Passport Size Picture'), ('ExperienceLetter', 'Experience Letter'), ('CV', 'CV'), ('LetterOfRecommendation', 'Letter of Recommendation'), ('Resume', 'Resume')], max_length=50),
        ),
    ]
